# Generated by Django 3.1.8 on 2021-08-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210828_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='debitcollection',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CreditCollection',
        ),
        migrations.DeleteModel(
            name='DebitCollection',
        ),
    ]
