# Generated by Django 3.1.8 on 2021-08-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210831_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.customer'),
        ),
    ]
