# Generated by Django 3.1.8 on 2021-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210901_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='due',
        ),
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('Credited', 'Credited'), ('Debited', 'Debited')], max_length=200, null=True),
        ),
    ]
