# Generated by Django 3.1.8 on 2021-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210915_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=200, null=True),
        ),
    ]
