# Generated by Django 3.1.8 on 2021-09-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210916_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.customer'),
        ),
    ]
